export const demoImages = {
  bomber: require('../../assets/demo/bomber-lilas.png'),
  dress: require('../../assets/demo/vestido-esmeralda.png'),
  sneakers: require('../../assets/demo/tenis-lavanda.png'),
  bag: require('../../assets/demo/bolsa-caramelo.png'),
  collection: require('../../assets/demo/colecao-essencial.png'),
  camisaMarfim: require('../../assets/demo/camisa-marfim.png'),
  calcaAreia: require('../../assets/demo/calca-areia.png'),
  saiaVinho: require('../../assets/demo/saia-vinho.png'),
  botaPreta: require('../../assets/demo/bota-preta.png'),
  casacoCamel: require('../../assets/demo/casaco-camelo.png'),
  joiasDouradas: require('../../assets/demo/joias-douradas.png'),
  blazerAreia: require('../../assets/demo/distinct/blazer-horizonte-areia-v2.jpg'),
  tricotVinho: require('../../assets/demo/distinct/tricot-gola-alta-vinho-v2.jpg'),
  regataPreta: require('../../assets/demo/distinct/regata-canelada-preta-v2.jpg'),
  coleteOffwhite: require('../../assets/demo/distinct/colete-alongado-brisa-v2.jpg'),
  camisaAzul: require('../../assets/demo/distinct/camisa-oxford-sereno-v2.jpg'),
  cardiganCaramelo: require('../../assets/demo/distinct/cardigan-botoes-dourados-v2.jpg'),
  topVerde: require('../../assets/demo/distinct/top-assimetrico-orvalho-v2.jpg'),
  jeansWide: require('../../assets/demo/distinct/jeans-wide-leg-indigo-v2.jpg'),
  calcaPreta: require('../../assets/demo/distinct/calca-cenoura-preta-v2.jpg'),
  saiaVerde: require('../../assets/demo/distinct/saia-midi-acetinada-verde-v2.jpg'),
  shortMarfim: require('../../assets/demo/distinct/short-alfaiataria-luz-v2.jpg'),
  calcaChumbo: require('../../assets/demo/distinct/calca-reta-grafite-v2.jpg'),
  saiaLilas: require('../../assets/demo/distinct/saia-evase-lavanda-v2.jpg'),
  jeansClaro: require('../../assets/demo/distinct/jeans-reto-horizonte-v2.jpg'),
  cargoOliva: require('../../assets/demo/distinct/calca-cargo-contorno-v2.jpg'),
  vestidoTerracota: require('../../assets/demo/distinct/vestido-midi-terracota-v2.jpg'),
  chemiseMarfim: require('../../assets/demo/distinct/chemise-aurora-marfim-v2.jpg'),
  envelopeVinho: require('../../assets/demo/distinct/vestido-envelope-rubi-v2.jpg'),
  macacaoPreto: require('../../assets/demo/distinct/macacao-pantalona-eclipse-v2.jpg'),
  vestidoLinho: require('../../assets/demo/distinct/vestido-linho-natural-v2.jpg'),
  assimetricoLilas: require('../../assets/demo/distinct/vestido-assimetrico-nevoa-v2.jpg'),
  macacaoVerde: require('../../assets/demo/distinct/macacao-pantalona-selva-v2.jpg'),
  tubinhoGrafite: require('../../assets/demo/distinct/vestido-tubinho-traco-v2.jpg'),
  floralRose: require('../../assets/demo/distinct/vestido-jardim-minimal-v2.jpg'),
  scarpinVinho: require('../../assets/demo/distinct/scarpin-rubi-v2.jpg'),
  sandaliaDourada: require('../../assets/demo/distinct/sandalia-luz-dourada-v2.jpg'),
  loaferCaramelo: require('../../assets/demo/distinct/loafer-contorno-caramelo-v2.jpg'),
  muleMarfim: require('../../assets/demo/distinct/mule-essencial-marfim-v2.jpg'),
  botaCafe: require('../../assets/demo/distinct/bota-cano-medio-terra-v2.jpg'),
  sapatilhaPreta: require('../../assets/demo/distinct/sapatilha-tela-urbana-v2.jpg'),
  sandaliaVerde: require('../../assets/demo/distinct/sandalia-bloco-esmeralda-v2.jpg'),
  tenisBranco: require('../../assets/demo/distinct/tenis-couro-alva-v2.jpg'),
  bolsaVinho: require('../../assets/demo/distinct/bolsa-mini-rubi-v2.jpg'),
  cintoCaramelo: require('../../assets/demo/distinct/cinto-couro-essencial-v2.jpg'),
  lencoVerde: require('../../assets/demo/distinct/lenco-seda-botanico-v2.jpg'),
  colarOrganico: require('../../assets/demo/distinct/colar-organico-luz-v2.jpg'),
  toteAreia: require('../../assets/demo/distinct/bolsa-tote-horizonte-v2.jpg'),
  oculosVinho: require('../../assets/demo/distinct/oculos-acetato-rubi-v2.jpg'),
  clutchPreta: require('../../assets/demo/distinct/clutch-eclipse-v2.jpg'),
  cintoDourado: require('../../assets/demo/distinct/cinto-fivela-escultural-v2.jpg'),
};

export const wardrobeCategories = [
  { id: 'tops', label: 'Parte de cima', examples: 'Blusas, camisas e jaquetas' },
  { id: 'bottoms', label: 'Parte de baixo', examples: 'Calças, saias e shorts' },
  { id: 'dresses', label: 'Peça única', examples: 'Vestidos e macacões' },
  { id: 'shoes', label: 'Calçados', examples: 'Tênis, botas e sandálias' },
  { id: 'accessories', label: 'Acessórios', examples: 'Bolsas, cintos e joias' },
];

const categoryLabels = {
  tops: 'Parte de cima',
  bottoms: 'Parte de baixo',
  dresses: 'Peça única',
  shoes: 'Calçados',
  accessories: 'Acessórios',
};

// 50 peças de demonstração: 10 por categoria, com metadados prontos para filtros e detalhes.
const wardrobeSeed = [
  // Parte de cima
  ['wardrobe-bomber', 'Bomber Nuvem Lilás', 'tops', 'Jaqueta', 'Lilás', 'M', 'Ateliê Aurora', 'bomber', 24],
  ['wardrobe-blazer-areia', 'Blazer Horizonte Areia', 'tops', 'Blazer', 'Areia', 'M', 'Meu armário', 'blazerAreia', 28],
  ['wardrobe-camisa-marfim', 'Camisa Fluida Marfim', 'tops', 'Camisa', 'Marfim', 'P', 'Casa Lume', 'camisaMarfim', 24],
  ['wardrobe-tricot-vinho', 'Tricot Gola Alta Vinho', 'tops', 'Tricot', 'Vinho', 'M', 'Studio Ímpar', 'tricotVinho', 28],
  ['wardrobe-regata-preta', 'Regata Canelada Essencial', 'tops', 'Regata', 'Preto', 'P', 'Meu armário', 'regataPreta', 24],
  ['wardrobe-colete-offwhite', 'Colete Alongado Brisa', 'tops', 'Colete', 'Off-white', 'G', 'Ateliê Aurora', 'coleteOffwhite', 28],
  ['wardrobe-camisa-azul', 'Camisa Oxford Sereno', 'tops', 'Camisa', 'Azul claro', 'M', 'Meu armário', 'camisaAzul', 24],
  ['wardrobe-cardigan-caramelo', 'Cardigan Botões Dourados', 'tops', 'Cardigan', 'Caramelo', 'G', 'Casa Lume', 'cardiganCaramelo', 28],
  ['wardrobe-top-verde', 'Top Assimétrico Orvalho', 'tops', 'Top', 'Verde oliva', 'P', 'Studio Ímpar', 'topVerde', 24],
  ['wardrobe-casaco-camelo', 'Casaco Longo Camel', 'tops', 'Casaco', 'Camel', 'M', 'Ateliê Aurora', 'casacoCamel', 32],

  // Parte de baixo
  ['wardrobe-calca-areia', 'Pantalona Alfaiatada Areia', 'bottoms', 'Calça', 'Areia', '40', 'Casa Lume', 'calcaAreia', 28],
  ['wardrobe-saia-vinho', 'Saia Plissada Rubi', 'bottoms', 'Saia', 'Vinho', 'M', 'Ateliê Aurora', 'saiaVinho', 28],
  ['wardrobe-jeans-wide', 'Jeans Wide Leg Índigo', 'bottoms', 'Calça jeans', 'Azul índigo', '42', 'Studio Ímpar', 'jeansWide', 32],
  ['wardrobe-calca-preta', 'Calça Cenoura Essencial', 'bottoms', 'Calça', 'Preto', '40', 'Meu armário', 'calcaPreta', 24],
  ['wardrobe-saia-verde', 'Saia Midi Acetinada', 'bottoms', 'Saia', 'Verde esmeralda', 'M', 'Casa Lume', 'saiaVerde', 28],
  ['wardrobe-short-marfim', 'Short de Alfaiataria Luz', 'bottoms', 'Short', 'Marfim', '38', 'Ateliê Aurora', 'shortMarfim', 24],
  ['wardrobe-calca-chumbo', 'Calça Reta Grafite', 'bottoms', 'Calça', 'Chumbo', '42', 'Meu armário', 'calcaChumbo', 28],
  ['wardrobe-saia-lilas', 'Saia Evasê Lavanda', 'bottoms', 'Saia', 'Lavanda', 'G', 'Studio Ímpar', 'saiaLilas', 24],
  ['wardrobe-jeans-claro', 'Jeans Reto Horizonte', 'bottoms', 'Calça jeans', 'Azul claro', '40', 'Meu armário', 'jeansClaro', 32],
  ['wardrobe-cargo-oliva', 'Calça Cargo Contorno', 'bottoms', 'Calça', 'Verde oliva', 'M', 'Studio Ímpar', 'cargoOliva', 28],

  // Peças únicas
  ['wardrobe-dress', 'Vestido Esmeralda', 'dresses', 'Vestido', 'Verde', 'M', 'Meu armário', 'dress', 28],
  ['wardrobe-vestido-terracota', 'Vestido Midi Terracota', 'dresses', 'Vestido', 'Terracota', 'G', 'Ateliê Aurora', 'vestidoTerracota', 32],
  ['wardrobe-chemise-marfim', 'Chemise Aurora Marfim', 'dresses', 'Chemise', 'Marfim', 'M', 'Casa Lume', 'chemiseMarfim', 28],
  ['wardrobe-envelope-vinho', 'Vestido Envelope Rubi', 'dresses', 'Vestido', 'Vinho', 'P', 'Casa Lume', 'envelopeVinho', 32],
  ['wardrobe-macacao-preto', 'Macacão Pantalona Eclipse', 'dresses', 'Macacão', 'Preto', 'M', 'Studio Ímpar', 'macacaoPreto', 28],
  ['wardrobe-vestido-linho', 'Vestido Linho Natural', 'dresses', 'Vestido', 'Areia', 'G', 'Meu armário', 'vestidoLinho', 24],
  ['wardrobe-assimetrico-lilas', 'Vestido Assimétrico Névoa', 'dresses', 'Vestido', 'Lilás', 'P', 'Ateliê Aurora', 'assimetricoLilas', 28],
  ['wardrobe-macacao-verde', 'Macacão Pantalona Selva', 'dresses', 'Macacão', 'Verde profundo', 'M', 'Casa Lume', 'macacaoVerde', 32],
  ['wardrobe-tubinho-grafite', 'Vestido Tubinho Traço', 'dresses', 'Vestido', 'Grafite', 'G', 'Studio Ímpar', 'tubinhoGrafite', 24],
  ['wardrobe-floral-rose', 'Vestido Jardim Minimal', 'dresses', 'Vestido', 'Rosé', 'M', 'Meu armário', 'floralRose', 28],

  // Calçados
  ['wardrobe-sneakers', 'Tênis Horizonte', 'shoes', 'Tênis', 'Creme e lavanda', '38', 'Studio Ímpar', 'sneakers', 32],
  ['wardrobe-bota-preta', 'Bota Couro Noturna', 'shoes', 'Bota', 'Preto', '37', 'Casa Lume', 'botaPreta', 28],
  ['wardrobe-scarpin-vinho', 'Scarpin Rubi', 'shoes', 'Scarpin', 'Vinho', '36', 'Casa Lume', 'scarpinVinho', 24],
  ['wardrobe-sandalia-dourada', 'Sandália Luz Dourada', 'shoes', 'Sandália', 'Dourado', '37', 'Ateliê Aurora', 'sandaliaDourada', 28],
  ['wardrobe-loafer-caramelo', 'Loafer Contorno', 'shoes', 'Loafer', 'Caramelo', '38', 'Meu armário', 'loaferCaramelo', 24],
  ['wardrobe-mule-marfim', 'Mule Essencial Marfim', 'shoes', 'Mule', 'Marfim', '36', 'Studio Ímpar', 'muleMarfim', 28],
  ['wardrobe-bota-cafe', 'Bota Cano Médio Terra', 'shoes', 'Bota', 'Café', '39', 'Meu armário', 'botaCafe', 32],
  ['wardrobe-sapatilha-preta', 'Sapatilha Tela Urbana', 'shoes', 'Sapatilha', 'Preto', '37', 'Studio Ímpar', 'sapatilhaPreta', 24],
  ['wardrobe-sandalia-verde', 'Sandália Bloco Esmeralda', 'shoes', 'Sandália', 'Verde', '38', 'Casa Lume', 'sandaliaVerde', 28],
  ['wardrobe-tenis-branco', 'Tênis Couro Alva', 'shoes', 'Tênis', 'Branco', '39', 'Ateliê Aurora', 'tenisBranco', 32],

  // Acessórios
  ['wardrobe-bag', 'Bolsa Traço', 'accessories', 'Bolsa', 'Caramelo', 'Único', 'Casa Lume', 'bag', 24],
  ['wardrobe-bolsa-vinho', 'Bolsa Mini Rubi', 'accessories', 'Bolsa', 'Vinho', 'Único', 'Casa Lume', 'bolsaVinho', 28],
  ['wardrobe-cinto-caramelo', 'Cinto Couro Essencial', 'accessories', 'Cinto', 'Caramelo', 'M', 'Meu armário', 'cintoCaramelo', 24],
  ['wardrobe-brincos-dourados', 'Conjunto Forma Dourada', 'accessories', 'Joias', 'Dourado', 'Único', 'Ateliê Aurora', 'joiasDouradas', 28],
  ['wardrobe-lenco-verde', 'Lenço Seda Botânico', 'accessories', 'Lenço', 'Verde esmeralda', 'Único', 'Casa Lume', 'lencoVerde', 24],
  ['wardrobe-colar-organico', 'Colar Orgânico Luz', 'accessories', 'Colar', 'Dourado', 'Único', 'Ateliê Aurora', 'colarOrganico', 28],
  ['wardrobe-tote-areia', 'Bolsa Tote Horizonte', 'accessories', 'Bolsa', 'Areia', 'Único', 'Studio Ímpar', 'toteAreia', 32],
  ['wardrobe-oculos-vinho', 'Óculos Acetato Rubi', 'accessories', 'Óculos', 'Vinho', 'Único', 'Studio Ímpar', 'oculosVinho', 24],
  ['wardrobe-clutch-preta', 'Clutch Eclipse', 'accessories', 'Bolsa', 'Preto', 'Único', 'Casa Lume', 'clutchPreta', 28],
  ['wardrobe-cinto-dourado', 'Cinto Fivela Escultural', 'accessories', 'Cinto', 'Preto e dourado', 'G', 'Meu armário', 'cintoDourado', 24],
];

export const initialWardrobe = wardrobeSeed.map(([
  id,
  name,
  categoryId,
  subcategory,
  color,
  size,
  source,
  imageKey,
  angles,
]) => ({
  id,
  name,
  categoryId,
  category: categoryLabels[categoryId],
  subcategory,
  color,
  size,
  source,
  image: demoImages[imageKey],
  model3d: { id: `3d-${id.replace('wardrobe-', '')}`, status: 'ready', angles },
}));

export const demoFeed = [
  {
    id: 'feed-store-edit',
    type: 'STORE_SHOWCASE',
    authorType: 'STORE',
    label: 'Curadoria da semana',
    title: 'Cores que conversam',
    author: 'Ateliê Aurora',
    description: 'Uma curadoria da loja com lavanda, verde profundo e neutros para uma semana versátil.',
    image: demoImages.collection,
    likes: 1284,
    favorites: 319,
  },
  {
    id: 'feed-bomber',
    type: 'PEÇA',
    authorType: 'STORE',
    label: 'Lançamento',
    title: 'Bomber Nuvem Lilás',
    author: 'Ateliê Aurora',
    description: 'Volume confortável e acabamento acetinado para meia-estação.',
    image: demoImages.bomber,
    likes: 742,
    favorites: 168,
  },
  {
    id: 'feed-dress',
    type: 'DESTAQUE',
    authorType: 'STORE',
    label: 'Coleção patrocinada',
    title: 'Noite Esmeralda',
    author: 'Casa Lume',
    description: 'Uma seleção elegante para eventos e encontros especiais.',
    image: demoImages.dress,
    likes: 956,
    favorites: 241,
  },
];

export const demoStores = [
  {
    id: 'store-aurora',
    store_name: 'Ateliê Aurora',
    initials: 'AA',
    tagline: 'Forma, cor e movimento',
    category: 'Moda contemporânea',
    location: 'São Paulo, SP',
    followers: 18400,
    brandColor: '#6E3155',
    cover: demoImages.collection,
    items: [
      { id: 'aurora-1', name: 'Bomber Nuvem Lilás', category: 'Jaquetas', price: 'R$ 489', image: demoImages.bomber },
      { id: 'aurora-2', name: 'Vestido Horizonte', category: 'Vestidos', price: 'R$ 629', image: demoImages.dress },
      { id: 'aurora-3', name: 'Bolsa Traço', category: 'Acessórios', price: 'R$ 349', image: demoImages.bag },
    ],
  },
  {
    id: 'store-lume',
    store_name: 'Casa Lume',
    initials: 'CL',
    tagline: 'Elegância para ocasiões especiais',
    category: 'Festa e acessórios',
    location: 'Belo Horizonte, MG',
    followers: 12300,
    brandColor: '#174D3B',
    cover: demoImages.dress,
    items: [
      { id: 'lume-1', name: 'Vestido Esmeralda', category: 'Vestidos', price: 'R$ 749', image: demoImages.dress },
      { id: 'lume-2', name: 'Bolsa Traço', category: 'Acessórios', price: 'R$ 329', image: demoImages.bag },
    ],
  },
  {
    id: 'store-impar',
    store_name: 'Studio Ímpar',
    initials: 'SÍ',
    tagline: 'O essencial fora do óbvio',
    category: 'Casual urbano',
    location: 'Curitiba, PR',
    followers: 9700,
    brandColor: '#765D9D',
    cover: demoImages.sneakers,
    items: [
      { id: 'impar-1', name: 'Tênis Horizonte', category: 'Calçados', price: 'R$ 419', image: demoImages.sneakers },
      { id: 'impar-2', name: 'Bomber Nuvem Lilás', category: 'Jaquetas', price: 'R$ 459', image: demoImages.bomber },
    ],
  },
];

export const sponsoredCollections = [
  {
    id: 'showcase-essential',
    storeId: 'store-aurora',
    title: 'Essenciais em Cores',
    store_name: 'Ateliê Aurora',
    campaign: 'Lançamento de inverno',
    description: 'Cinco combinações para multiplicar as possibilidades do armário.',
    pieces: 12,
    rating: 4.9,
    image: demoImages.collection,
  },
  {
    id: 'showcase-night',
    storeId: 'store-lume',
    title: 'Noite Esmeralda',
    store_name: 'Casa Lume',
    campaign: 'Seleção patrocinada',
    description: 'Vestidos e acessórios em tons profundos para ocasiões especiais.',
    pieces: 8,
    rating: 4.8,
    image: demoImages.dress,
  },
  {
    id: 'showcase-weekend',
    storeId: 'store-impar',
    title: 'Fim de Semana Leve',
    store_name: 'Studio Ímpar',
    campaign: 'Novidades da marca',
    description: 'Conforto, cor e movimento em uma seleção casual.',
    pieces: 10,
    rating: 4.7,
    image: demoImages.sneakers,
  },
];

// Compatibilidade com a tela antiga durante a migração.
export const initialShowcases = sponsoredCollections;

export const initialPersonalCollections = [
  {
    id: 'personal-work',
    title: 'Semana de trabalho',
    occasion: 'Profissional',
    itemIds: ['wardrobe-bomber', 'wardrobe-dress', 'wardrobe-bag'],
    image: demoImages.collection,
  },
  {
    id: 'personal-weekend',
    title: 'Fim de semana confortável',
    occasion: 'Casual',
    itemIds: ['wardrobe-sneakers', 'wardrobe-bomber'],
    image: demoImages.sneakers,
  },
];

export const initialProfile = {
  name: 'Marina Alves',
  age: '34',
  profession: 'Consultora de negócios',
  bodyShape: 'Ampulheta',
  hairStyle: 'Coque',
  mannequinTop: 'M / 40',
  mannequinBottom: '42',
  bust: '94',
  waist: '76',
  hips: '104',
  height: '168',
};

export const featuredAd = {
  id: 'showcase-essential',
  storeId: 'store-aurora',
  eyebrow: 'AD • CONTEÚDO PATROCINADO',
  title: 'Essenciais em Cores',
  storeName: 'Ateliê Aurora',
  description: 'Uma curadoria de inverno pensada para combinar com o que já existe no seu armário.',
  cta: 'VER COLEÇÃO NA VITRINE',
  image: demoImages.collection,
};
