import Joi from 'joi';
import { pool, query } from '../config/db.js';
import { uuid, validate } from '../utils/validation.js';
import { authorizeInstitutionalCapability } from '../services/authorizationService.js';
import { HttpError } from '../utils/http.js';

const methodologySchema=Joi.object({key:Joi.string().trim().min(1).max(120).required(),technicalName:Joi.string().trim().min(1).max(160).required()});
const versionSchema=Joi.object({version:Joi.number().integer().min(1).required(),contentRef:Joi.string().trim().min(1).max(500).required(),contentHash:Joi.string().lowercase().pattern(/^[0-9a-f]{64}$/).allow(null)});
const dto=row=>({id:row.id,methodologyId:row.methodology_id,version:row.version,status:row.status,createdAt:row.created_at,publishedAt:row.published_at});
export async function create(req,res){const b=validate(methodologySchema,req.body);await authorizeInstitutionalCapability(req.auth,'impar.methodology.manage');const row=(await query("INSERT INTO methodologies(key,technical_name) VALUES($1,$2) RETURNING id,key,technical_name,status,created_at",[b.key,b.technicalName])).rows[0];res.status(201).json({id:row.id,key:row.key,technicalName:row.technical_name,status:row.status,createdAt:row.created_at});}
export async function createVersion(req,res){const b=validate(versionSchema,req.body);await authorizeInstitutionalCapability(req.auth,'impar.methodology.manage');const row=(await query(`INSERT INTO methodology_versions(methodology_id,version,content_ref,content_hash,created_by_principal_id)
 VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.params.methodologyId,b.version,b.contentRef,b.contentHash??null,req.auth.principalId])).rows[0];res.status(201).json(dto(row));}
export async function publish(req,res){validate(Joi.object({}),req.body||{});const c=await pool.connect();try{await c.query('BEGIN');await authorizeInstitutionalCapability(req.auth,'impar.methodology.manage',c);const v=(await c.query('SELECT * FROM methodology_versions WHERE id=$1 FOR UPDATE',[req.params.versionId])).rows[0];if(!v)throw new HttpError(404,'MethodologyVersion não encontrada');if(v.status==='PUBLISHED'){await c.query('COMMIT');return res.json(dto(v));}if(v.status!=='DRAFT')throw new HttpError(409,'MethodologyVersion não pode ser publicada');const row=(await c.query("UPDATE methodology_versions SET status='PUBLISHED',published_by_principal_id=$2,published_at=now() WHERE id=$1 RETURNING *",[v.id,req.auth.principalId])).rows[0];await c.query('COMMIT');res.json(dto(row));}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function retire(req,res){validate(Joi.object({}),req.body||{});await authorizeInstitutionalCapability(req.auth,'impar.methodology.manage');const row=(await query("UPDATE methodology_versions SET status='RETIRED' WHERE id=$1 AND status='PUBLISHED' RETURNING *",[req.params.versionId])).rows[0];if(!row)throw new HttpError(409,'MethodologyVersion não pode ser retirada');res.json(dto(row));}
export async function get(req,res){await authorizeInstitutionalCapability(req.auth,'impar.methodology.manage');const row=(await query('SELECT * FROM methodology_versions WHERE id=$1',[req.params.versionId])).rows[0];if(!row)throw new HttpError(404,'MethodologyVersion não encontrada');res.json(dto(row));}
