import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { asyncHandler } from '../utils/http.js';
import { requireAuth } from '../middleware/auth.js';
import { requireCapability } from '../services/authorizationService.js';
import { upload, uploadBudget, validateImages } from '../middleware/upload.js';
import * as auth from '../controllers/authController.js';
import * as stores from '../controllers/storeController.js';
import * as items from '../controllers/itemController.js';
import * as social from '../controllers/socialController.js';
import * as showcases from '../controllers/showcaseController.js';
import * as wardrobe from '../controllers/wardrobeController.js';
import * as profile from '../controllers/profileController.js';
import * as memberships from '../controllers/membershipController.js';
import * as storeRequests from '../controllers/storeRequestController.js';
import * as looks from '../controllers/lookController.js';
import * as contexts from '../controllers/contextController.js';
import * as media from '../services/imageService.js';
import * as reconstruction from '../controllers/reconstructionController.js';

const r=Router(), wrap=asyncHandler, cap=requireCapability;
const authLimit=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:'draft-7',legacyHeaders:false});
const photos=[uploadBudget,upload.array('photos',4),validateImages];
r.get('/reconstruction/protocol',requireAuth,wrap(reconstruction.protocol));
r.get('/reconstruction/jobs',requireAuth,wrap(reconstruction.list));
r.get('/reconstruction/sessions/:id',requireAuth,wrap(reconstruction.captureSession));
r.post('/reconstruction/jobs',requireAuth,wrap(reconstruction.create));
r.get('/reconstruction/jobs/:id',requireAuth,wrap(reconstruction.get));
r.post('/reconstruction/jobs/:id/inputs',requireAuth,...photos,wrap(reconstruction.inputs));
r.delete('/reconstruction/jobs/:id/inputs/:mediaId',requireAuth,wrap(reconstruction.removeInput));
r.post('/reconstruction/jobs/:id/submit',requireAuth,wrap(reconstruction.submit));
r.get('/reconstruction/jobs/:id/output',requireAuth,wrap(reconstruction.output));
r.post('/reconstruction/jobs/:id/inspection',requireAuth,wrap(reconstruction.inspect));
r.post('/auth/register',authLimit,wrap(auth.register));
r.post('/auth/login',authLimit,wrap(auth.login));
r.get('/auth/me',requireAuth,wrap(auth.me));
r.post('/auth/logout',requireAuth,wrap(auth.logout));
r.get('/stores',wrap(stores.listStores));
r.get('/stores/me',requireAuth,cap('store.read'),wrap(stores.myStore));
r.put('/stores/me',requireAuth,cap('store.update'),wrap(stores.updateStore));
r.get('/stores/engagement/saves',requireAuth,cap('analytics.read'),wrap(stores.storeEngagement));
r.post('/stores/items',requireAuth,cap('catalog.write'),...photos,wrap(stores.createStoreItems));
r.post('/store-requests',requireAuth,wrap(storeRequests.create));
r.get('/store-requests',requireAuth,wrap(storeRequests.list));
r.post('/store-requests/:id/submit',requireAuth,wrap(storeRequests.submit));
r.post('/store-requests/:id/review',requireAuth,wrap(storeRequests.review));
r.get('/stores/:storeId/memberships',requireAuth,cap('members.manage'),wrap(memberships.list));
r.post('/stores/:storeId/memberships',requireAuth,cap('members.manage'),wrap(memberships.assign));
r.delete('/stores/:storeId/memberships/:membershipId',requireAuth,cap('members.manage'),wrap(memberships.revoke));
r.get('/stores/:id',wrap(stores.getStore));
r.get('/products',wrap(items.listItems));
r.get('/products/:id/media/:mediaId',wrap(media.readCatalogMedia));
r.post('/products/:id/save',requireAuth,wrap(items.saveProduct));
r.delete('/products/:id/save',requireAuth,wrap(items.removeSave));
r.get('/commercial-saves',requireAuth,wrap(items.listSaves));
r.get('/items',requireAuth,wrap(items.listItems));
r.post('/items',requireAuth,...photos,wrap(items.createWardrobeItem));
r.post('/items/:id/copy-to-wardrobe',requireAuth,wrap(items.legacyCopy));
r.get('/wardrobe/items',requireAuth,wrap(items.listWardrobe));
r.post('/wardrobe/items',requireAuth,...photos,wrap(items.createWardrobeItem));
r.get('/wardrobe/items/:id',requireAuth,wrap(items.getWardrobeItem));
r.get('/wardrobe/legacy-reviews',requireAuth,wrap(items.legacyReviews));
r.get('/wardrobe/capacity',requireAuth,wrap(wardrobe.capacity));
r.post('/wardrobe/upgrade-requests',requireAuth,wrap(wardrobe.requestUpgrade));
r.get('/profile',requireAuth,wrap(profile.getProfile));
r.put('/profile',requireAuth,wrap(profile.updateProfile));
r.post('/profile/photo',requireAuth,uploadBudget,upload.single('photo'),validateImages,wrap(profile.uploadProfilePhoto));
r.post('/contexts',requireAuth,wrap(contexts.create));
r.get('/media/:id',requireAuth,wrap(media.readMedia));
r.post('/media/:id/access',requireAuth,wrap(media.mediaAccess));
r.get('/looks',requireAuth,wrap(looks.list));
r.post('/looks',requireAuth,wrap(looks.create));
r.get('/look-variations/:id',requireAuth,wrap(looks.getVariation));
r.get('/looks/:id',requireAuth,wrap(looks.get));
r.post('/looks/:id/versions',requireAuth,wrap(looks.addVersion));
r.post('/looks/:id/variations',requireAuth,wrap(looks.createVariation));
r.get('/looks/:id/variations',requireAuth,wrap(looks.listVariations));
r.post('/looks/:lookId/contexts/:contextId',requireAuth,wrap(contexts.linkLook));
r.post('/stores/:id/follow',requireAuth,wrap(social.followStore));
r.delete('/stores/:id/follow',requireAuth,wrap(social.unfollowStore));
const retired=(_req,res)=>res.set('Deprecation','true').status(410).json({error:'Fluxo social descontinuado',code:'ENDPOINT_RETIRED'});
r.post('/users/:id/follow',requireAuth,retired);
r.get('/feed',requireAuth,wrap(social.feed));
r.get('/showcases',wrap(showcases.listShowcases));
r.post('/showcases',requireAuth,cap('marketing.write'),wrap(showcases.createShowcase));
r.post('/showcases/:id/comments',requireAuth,retired);
export default r;
