import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { HttpError } from '../utils/http.js';
import { asyncHandler } from '../utils/http.js';
import { requireAuth } from '../middleware/auth.js';
import { requireCapability } from '../services/authorizationService.js';
import { upload, uploadBudget, validateImages } from '../middleware/upload.js';
import * as auth from '../controllers/authController.js';
import * as stores from '../controllers/storeController.js';
import * as items from '../controllers/itemController.js';
import * as social from '../controllers/socialController.js';
import * as showcases from '../controllers/showcaseController.js';
import * as wardrobe from '../controllers/wardrobeController.js';
import * as profile from '../controllers/profileController.js';
import * as memberships from '../controllers/membershipController.js';
import * as storeRequests from '../controllers/storeRequestController.js';
import * as looks from '../controllers/lookController.js';
import * as contexts from '../controllers/contextController.js';
import * as collections from '../controllers/collectionController.js';
import * as comparisons from '../controllers/comparisonController.js';
import * as imparAnalyses from '../controllers/imparAnalysisController.js';
import * as imparAnalysisJobs from '../controllers/imparAnalysisJobController.js';
import * as imparAnalysisRequests from '../controllers/imparAnalysisRequestController.js';
import * as methodologies from '../controllers/methodologyController.js';
import * as knowledge from '../controllers/knowledgeController.js';
import * as media from '../services/imageService.js';
import * as reconstruction from '../controllers/reconstructionController.js';

const r=Router(), wrap=asyncHandler, cap=requireCapability;
const authLimit=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:'draft-7',legacyHeaders:false,handler:(_req,_res,next)=>next(new HttpError(429,'Rate limited'))});
const photos=[uploadBudget,upload.array('photos',4),validateImages];
r.get('/reconstruction/protocol',requireAuth,wrap(reconstruction.protocol));
r.get('/reconstruction/jobs',requireAuth,wrap(reconstruction.list));
r.get('/reconstruction/sessions/:id',requireAuth,wrap(reconstruction.captureSession));
r.post('/reconstruction/jobs',requireAuth,wrap(reconstruction.create));
r.get('/reconstruction/jobs/:id',requireAuth,wrap(reconstruction.get));
r.post('/reconstruction/jobs/:id/inputs',requireAuth,...photos,wrap(reconstruction.inputs));
r.delete('/reconstruction/jobs/:id/inputs/:mediaId',requireAuth,wrap(reconstruction.removeInput));
r.post('/reconstruction/jobs/:id/submit',requireAuth,wrap(reconstruction.submit));
r.post('/reconstruction/jobs/:id/retry',requireAuth,wrap(reconstruction.retry));
r.post('/reconstruction/jobs/:id/cancel',requireAuth,wrap(reconstruction.cancel));
r.get('/reconstruction/jobs/:id/output',requireAuth,wrap(reconstruction.output));
r.post('/reconstruction/jobs/:id/inspection',requireAuth,wrap(reconstruction.inspect));
r.post('/impar-analyses/:analysisId/requests',requireAuth,wrap(imparAnalysisRequests.request));
r.get('/impar-analyses/:analysisId/request',requireAuth,wrap(imparAnalysisRequests.get));
r.post('/impar-analyses/:analysisId/request/cancel',requireAuth,wrap(imparAnalysisRequests.cancel));
r.post('/impar-analyses/:analysisId/jobs',requireAuth,wrap(imparAnalysisJobs.enqueue));
r.get('/impar-analyses/:analysisId/jobs/:jobId',requireAuth,wrap(imparAnalysisJobs.get));
r.post('/impar-analyses/:analysisId/jobs/:jobId/retry',requireAuth,wrap(imparAnalysisJobs.retry));
r.post('/impar-analyses/:analysisId/jobs/:jobId/cancel',requireAuth,wrap(imparAnalysisJobs.cancel));
r.post('/auth/register',authLimit,wrap(auth.register));
r.post('/auth/login',authLimit,wrap(auth.login));
r.get('/auth/me',requireAuth,wrap(auth.me));
r.post('/auth/logout',requireAuth,wrap(auth.logout));
r.get('/stores',wrap(stores.listStores));
r.get('/stores/me',requireAuth,cap('store.read'),wrap(stores.myStore));
r.put('/stores/me',requireAuth,cap('store.update'),wrap(stores.updateStore));
r.get('/stores/engagement/saves',requireAuth,cap('analytics.read'),wrap(stores.storeEngagement));
r.post('/stores/items',requireAuth,cap('catalog.write'),...photos,wrap(stores.createStoreItems));
r.post('/store-requests',requireAuth,wrap(storeRequests.create));
r.get('/store-requests',requireAuth,wrap(storeRequests.list));
r.post('/store-requests/:id/submit',requireAuth,wrap(storeRequests.submit));
r.post('/store-requests/:id/review',requireAuth,wrap(storeRequests.review));
r.get('/stores/:storeId/memberships',requireAuth,cap('members.manage'),wrap(memberships.list));
r.post('/stores/:storeId/memberships',requireAuth,cap('members.manage'),wrap(memberships.assign));
r.delete('/stores/:storeId/memberships/:membershipId',requireAuth,cap('members.manage'),wrap(memberships.revoke));
r.get('/stores/:id',wrap(stores.getStore));
r.get('/products',wrap(items.listItems));
r.get('/products/:id/media/:mediaId',wrap(media.readCatalogMedia));
r.post('/products/:id/save',requireAuth,wrap(items.saveProduct));
r.delete('/products/:id/save',requireAuth,wrap(items.removeSave));
r.get('/commercial-saves',requireAuth,wrap(items.listSaves));
r.get('/items',requireAuth,wrap(items.listItems));
r.post('/items',requireAuth,...photos,wrap(items.createWardrobeItem));
r.post('/items/:id/copy-to-wardrobe',requireAuth,wrap(items.legacyCopy));
r.get('/wardrobe/items',requireAuth,wrap(items.listWardrobe));
r.post('/wardrobe/items',requireAuth,...photos,wrap(items.createWardrobeItem));
r.get('/wardrobe/items/:id',requireAuth,wrap(items.getWardrobeItem));
r.get('/wardrobe/legacy-reviews',requireAuth,wrap(items.legacyReviews));
r.get('/wardrobe/capacity',requireAuth,wrap(wardrobe.capacity));
r.post('/wardrobe/upgrade-requests',requireAuth,wrap(wardrobe.requestUpgrade));
r.get('/profile',requireAuth,wrap(profile.getProfile));
r.put('/profile',requireAuth,wrap(profile.updateProfile));
r.post('/profile/photo',requireAuth,uploadBudget,upload.single('photo'),validateImages,wrap(profile.uploadProfilePhoto));
r.post('/contexts',requireAuth,wrap(contexts.create));
r.get('/contexts/:contextId',requireAuth,wrap(contexts.get));
r.post('/impar-analyses',requireAuth,wrap(imparAnalyses.create));
r.get('/impar-analyses',requireAuth,wrap(imparAnalyses.list));
r.get('/impar-analyses/:analysisId',requireAuth,wrap(imparAnalyses.get));
r.post('/impar-analyses/:analysisId/complete',requireAuth,wrap(imparAnalyses.complete));
r.post('/impar-analyses/:analysisId/results',requireAuth,wrap(imparAnalyses.createResult));
r.get('/impar-analyses/:analysisId/results',requireAuth,wrap(imparAnalyses.listResults));
r.post('/impar-analyses/:analysisId/results/:resultId/finalize',requireAuth,wrap(imparAnalyses.finalizeResult));
r.post('/impar-analyses/:analysisId/methodology',requireAuth,wrap(imparAnalyses.assignMethodology));
r.post('/methodologies',requireAuth,wrap(methodologies.create));
r.post('/methodologies/:methodologyId/versions',requireAuth,wrap(methodologies.createVersion));
r.get('/methodology-versions/:versionId',requireAuth,wrap(methodologies.get));
r.post('/methodology-versions/:versionId/publish',requireAuth,wrap(methodologies.publish));
r.post('/methodology-versions/:versionId/retire',requireAuth,wrap(methodologies.retire));
r.post('/knowledge-sources',requireAuth,wrap(knowledge.source));r.post('/knowledge-sources/:sourceId/candidates',requireAuth,wrap(knowledge.candidate));r.post('/knowledge-candidates/:candidateId/submit',requireAuth,wrap(knowledge.submit));r.post('/knowledge-candidates/:candidateId/review',requireAuth,wrap(knowledge.review));r.post('/knowledge-candidates/:candidateId/publish',requireAuth,wrap(knowledge.publish));r.post('/methodology-versions/:versionId/knowledge',requireAuth,wrap(knowledge.bind));
r.post('/authorized-knowledge-versions/:versionId/retire',requireAuth,wrap(knowledge.retire));
r.post('/collections',requireAuth,wrap(collections.create));
r.post('/collections/:collectionId/looks/:lookId',requireAuth,wrap(collections.linkLook));
r.get('/collections/:collectionId',requireAuth,wrap(collections.get));
r.get('/collections/:collectionId/looks',requireAuth,wrap(collections.listLooks));
r.post('/comparisons',requireAuth,wrap(comparisons.create));
r.post('/comparisons/:comparisonId/evaluations',requireAuth,wrap(comparisons.createEvaluation));
r.post('/comparisons/:comparisonId/evaluations/:evaluationId/criteria',requireAuth,wrap(comparisons.createEvaluationCriterion));
r.post('/comparisons/:comparisonId/evaluations/:evaluationId/results',requireAuth,wrap(comparisons.createEvaluationResult));
r.get('/comparisons/:comparisonId/evaluations/:evaluationId',requireAuth,wrap(comparisons.getEvaluation));
r.post('/comparisons/:comparisonId/evaluations/:evaluationId/complete',requireAuth,wrap(comparisons.completeEvaluation));
r.post('/comparisons/:comparisonId/looks/:lookId',requireAuth,wrap(comparisons.linkLook));
r.get('/comparisons/:comparisonId',requireAuth,wrap(comparisons.get));
r.get('/comparisons/:comparisonId/looks',requireAuth,wrap(comparisons.listLooks));
r.get('/media/:id',requireAuth,wrap(media.readMedia));
r.post('/media/:id/access',requireAuth,wrap(media.mediaAccess));
r.get('/looks',requireAuth,wrap(looks.list));
r.post('/looks',requireAuth,wrap(looks.create));
r.get('/look-variations/:id',requireAuth,wrap(looks.getVariation));
r.get('/looks/:id',requireAuth,wrap(looks.get));
r.post('/looks/:id/versions',requireAuth,wrap(looks.addVersion));
r.post('/looks/:id/variations',requireAuth,wrap(looks.createVariation));
r.get('/looks/:id/variations',requireAuth,wrap(looks.listVariations));
r.post('/looks/:lookId/contexts/:contextId',requireAuth,wrap(contexts.linkLook));
r.get('/looks/:lookId/contexts',requireAuth,wrap(contexts.listForLook));
r.post('/stores/:id/follow',requireAuth,wrap(social.followStore));
r.delete('/stores/:id/follow',requireAuth,wrap(social.unfollowStore));
const retired=(_req,res,next)=>{
  res.set('Deprecation','true');
  next(new HttpError(410,'Endpoint retired',{code:'STATE_CONFLICT'}));
};
r.post('/users/:id/follow',requireAuth,retired);
r.get('/feed',requireAuth,wrap(social.feed));
r.get('/showcases',wrap(showcases.listShowcases));
r.post('/showcases',requireAuth,cap('marketing.write'),wrap(showcases.createShowcase));
r.post('/showcases/:id/comments',requireAuth,retired);
export default r;
