import { Router } from 'express'; import { asyncHandler } from '../utils/http.js'; import { requireAuth, requireRole } from '../middleware/auth.js'; import { upload } from '../middleware/upload.js';
import * as auth from '../controllers/authController.js'; import * as stores from '../controllers/storeController.js'; import * as items from '../controllers/itemController.js'; import * as social from '../controllers/socialController.js'; import * as showcases from '../controllers/showcaseController.js';
const r=Router();
r.post('/auth/register',asyncHandler(auth.register)); r.post('/auth/login',asyncHandler(auth.login)); r.get('/auth/me',requireAuth,asyncHandler(auth.me));
r.get('/stores',asyncHandler(stores.listStores)); r.get('/stores/me',requireAuth,requireRole('STORE'),asyncHandler(stores.myStore)); r.put('/stores/me',requireAuth,requireRole('STORE'),asyncHandler(stores.updateStore)); r.get('/stores/engagement/saves',requireAuth,requireRole('STORE'),asyncHandler(stores.storeEngagement)); r.get('/stores/:id',asyncHandler(stores.getStore)); r.post('/stores/items',requireAuth,requireRole('STORE'),upload.array('photos',20),asyncHandler(stores.createStoreItems));
r.get('/items',requireAuth,asyncHandler(items.listItems)); r.post('/items',requireAuth,requireRole('PERSON'),upload.array('photos',10),asyncHandler(items.createWardrobeItem)); r.post('/items/:id/copy-to-wardrobe',requireAuth,requireRole('PERSON'),asyncHandler(items.copyStoreItem));
r.post('/stores/:id/follow',requireAuth,asyncHandler(social.followStore)); r.delete('/stores/:id/follow',requireAuth,asyncHandler(social.unfollowStore)); r.post('/users/:id/follow',requireAuth,asyncHandler(social.followUser)); r.get('/feed',requireAuth,asyncHandler(social.feed));
r.get('/showcases',asyncHandler(showcases.listShowcases)); r.post('/showcases',requireAuth,requireRole('STORE'),asyncHandler(showcases.createShowcase)); r.post('/showcases/:id/comments',requireAuth,asyncHandler(showcases.commentShowcase));
export default r;
